/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.hrapp.ui;

import com.vektorel.hrapp.entity.Bolum;
import com.vektorel.hrapp.entity.Kisi;
import com.vektorel.hrapp.service.BolumService;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author soner
 */
public class frmBolumEkle extends javax.swing.JDialog {

    BolumService bolumService = new BolumService();

    /**
     * Creates new form frmBolumEkle
     */
    public frmBolumEkle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        bolumTabloDoldur();

    }

    frmBolumEkle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBolumKodu = new javax.swing.JLabel();
        txtBolumKodu = new javax.swing.JTextField();
        lblBolumAdi = new javax.swing.JLabel();
        txtBolumAdi = new javax.swing.JTextField();
        btnBolumIptal = new javax.swing.JButton();
        btnBolumKaydet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBolum = new javax.swing.JTable();
        btnBolumGuncelle = new javax.swing.JButton();
        btnBolumSil = new javax.swing.JButton();
        lblBolumId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBolumKodu.setText("Bölüm Kodu");

        lblBolumAdi.setText("Bölüm Tanımı");

        btnBolumIptal.setText("Kapat");
        btnBolumIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolumIptalActionPerformed(evt);
            }
        });

        btnBolumKaydet.setText("Kaydet");
        btnBolumKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolumKaydetActionPerformed(evt);
            }
        });

        tblBolum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBolum);

        btnBolumGuncelle.setText("Güncelle");
        btnBolumGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolumGuncelleActionPerformed(evt);
            }
        });

        btnBolumSil.setText("Sil");
        btnBolumSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolumSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBolumAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBolumKodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBolumAdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(txtBolumKodu, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBolumKaydet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBolumGuncelle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBolumSil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBolumIptal)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBolumId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblBolumId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBolumKodu)
                    .addComponent(txtBolumKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBolumAdi)
                    .addComponent(txtBolumAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBolumIptal)
                    .addComponent(btnBolumKaydet)
                    .addComponent(btnBolumGuncelle)
                    .addComponent(btnBolumSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBolumIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolumIptalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBolumIptalActionPerformed

    private void btnBolumKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolumKaydetActionPerformed
        try {
            if (lblBolumId.getText().trim().equals("")) {
                bolumService.save(new Bolum(null, txtBolumKodu.getText(), txtBolumAdi.getText()));
            } else {
                bolumService.update(new Bolum(new Long(lblBolumId.getText()), txtBolumKodu.getText(), txtBolumAdi.getText()));
            }
            bolumTabloDoldur();
            
            txtBolumKodu.setText("");
            txtBolumAdi.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBolumKaydetActionPerformed

    private void btnBolumGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolumGuncelleActionPerformed
        int secilikayit = tblBolum.getSelectedRow();
        if (secilikayit > -1) {
            String value = tblBolum.getValueAt(secilikayit, 0).toString();
            Bolum bolum = bolumService.getById(new Long(value));

            lblBolumId.setText(bolum.getId().toString());
            txtBolumKodu.setText(bolum.getKod());
            txtBolumAdi.setText(bolum.getTanim());
        }

    }//GEN-LAST:event_btnBolumGuncelleActionPerformed

    private void btnBolumSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolumSilActionPerformed
        int secilikayit = tblBolum.getSelectedRow();
        if (secilikayit > -1) {
            String value = tblBolum.getValueAt(secilikayit, 0).toString();
            Bolum bolum = bolumService.getById(new Long(value));
            try {
                bolumService.delete(bolum);
                bolumTabloDoldur();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnBolumSilActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBolumGuncelle;
    private javax.swing.JButton btnBolumIptal;
    private javax.swing.JButton btnBolumKaydet;
    private javax.swing.JButton btnBolumSil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBolumAdi;
    private javax.swing.JLabel lblBolumId;
    private javax.swing.JLabel lblBolumKodu;
    private javax.swing.JTable tblBolum;
    private javax.swing.JTextField txtBolumAdi;
    private javax.swing.JTextField txtBolumKodu;
    // End of variables declaration//GEN-END:variables

    private void bolumTabloDoldur() {
        List<Bolum> bolum = bolumService.getAll(null);
        String[][] data = new String[bolum.size()][8];
        for (int i = 0; i < bolum.size(); i++) {
            data[i][0] = bolum.get(i).getId().toString();
            data[i][1] = bolum.get(i).getKod();
            data[i][2] = bolum.get(i).getTanim();
        }

        tblBolum.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Id", "Bölüm Kodu", "Bölüm Tanımı"
                }
        ));

    }

}
