package com.vektorel.hrapp.ui;

import com.vektorel.hrapp.entity.Cinsiyet;
import com.vektorel.hrapp.entity.Cv;
import com.vektorel.hrapp.entity.Fotograf;
import com.vektorel.hrapp.service.CvService;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author eaytac
 */
public class frmCv extends javax.swing.JFrame {

    byte[] fotografDosyasi;
    String fotografDosyaAdresi;

    /**
     * Creates new form frmCv
     */
    public frmCv() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public frmCv(Cv cv) {
        initComponents();
        setLocationRelativeTo(null);

        txtCvTanimi.setText(cv.getCvTanimi());
        lblId.setText(cv.getId().toString());
        txtAd.setText(cv.getAd());
        txtSoyad.setText(cv.getSoyad());
        txtEposta.setText(cv.getEposta());
        txtTCKimlikNo.setText(cv.getTcKimlikNo().toString());
        txtDogumTarihi.setDate(cv.getDogumTarihi());

        JComboBox<Cinsiyet> cmbCinsiyet = new JComboBox(); //BU KISIM ÇALIŞMIYOR!!
        cmbCinsiyet.setModel(new DefaultComboBoxModel(cv.getCinsiyet().values()));

        txtAdres.setText(cv.getAdres());

//        cmbIl.setSelectedIndex(toIntExact(cv.getIl().getId()) - 1);
//        cmbIlce.setSelectedIndex(toIntExact(cv.getIlce().getId()) - 1);
//        cmbOkul.setSelectedIndex(toIntExact(cv.getOkul().getId()) - 1);
        Fotograf fotograf = cv.getFotograf();
        byte[] foto = fotograf.getImage();
        ImageIcon image = new ImageIcon(foto);
        Image im = image.getImage();
        Image myImg = im.getScaledInstance(lblFotograf.getWidth(), lblFotograf.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        lblFotograf.setIcon(newImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEposta = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        txtTCKimlikNo = new javax.swing.JTextField();
        txtDogumTarihi = new com.toedter.calendar.JDateChooser();
        cmbCinsiyet = new javax.swing.JComboBox<>();
        txtAdres = new javax.swing.JTextField();
        cmbIl = new javax.swing.JComboBox<>();
        cmbIlce = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lblFotograf = new javax.swing.JLabel();
        btnFotografSec = new javax.swing.JButton();
        btnIptal = new javax.swing.JButton();
        btnKaydet = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCvTanimi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbOkul = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbBolum = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        jLabel3.setText("E-Posta adresi:");

        jLabel4.setText("Adres:");

        jLabel5.setText("T.C. Kimlik No:");

        jLabel6.setText("Doğum Tarihi:");

        jLabel7.setText("Cinsiyet:");

        jLabel8.setText("İl:");

        jLabel9.setText("İlçe:");

        txtDogumTarihi.setDateFormatString("dd.MM.yyyy");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CV Bilgileri");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFotograf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnFotografSec.setText("Fotoğraf Seç");
        btnFotografSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotografSecActionPerformed(evt);
            }
        });

        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        jLabel11.setText("Kullanıcı ID:");

        lblId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("CV Tanımı:");

        jLabel13.setText("Mezun Olduğu Okul:");

        jLabel14.setText("Mezun Olduğu Bölüm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTCKimlikNo)
                                    .addComponent(txtEposta)
                                    .addComponent(cmbCinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAdres)
                                    .addComponent(cmbIl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbIlce, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbOkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDogumTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnIptal)
                                        .addGap(72, 72, 72)
                                        .addComponent(btnKaydet))
                                    .addComponent(cmbBolum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFotografSec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFotograf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCvTanimi))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCvTanimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtEposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtTCKimlikNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(txtDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(cmbCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(cmbIl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(cmbIlce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(cmbOkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFotograf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFotografSec)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKaydet)
                            .addComponent(btnIptal))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        int secim = JOptionPane.showConfirmDialog(rootPane, "Çıkmak istediğinizden emin misiniz? Kaydedilmemiş veriler kaybedilecek!!!", "Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (secim == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnIptalActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        try {
            CvService cvService = new CvService();
            Cv cv = new Cv();
            Date date = new Date();

            cv.setCvTanimi(txtCvTanimi.getText());
            cv.setAd(txtAd.getText());
            cv.setSoyad(txtSoyad.getText());
            cv.setEposta(txtEposta.getText());
            cv.setTcKimlikNo(new Long(txtTCKimlikNo.getText()));
            cv.setDogumTarihi(txtDogumTarihi.getDate());

            if (cv.getCvEklenmeTarihi() == null) { //Veritabanında iş başvuru tarihi yoksa kaydet
                cv.setCvEklenmeTarihi(date); // Formun kaydedildiği tarih iş başvuru tarihi olarak kabul edilecek!
            }
//            cv.setCinsiyet(cmbCinsiyet.getSelectedIndex());
            cv.setAdres(txtAdres.getText());
//            cv.setIl(cmbIl.getSelectedIndex());
//            cv.setIlce(cmbIlce.getSelectedIndex());
//            cv.setOkul(cmbOkul.getSelectedIndex());

            //Fotoğrafı veritabanına kaydetme aşamaları
            FileInputStream fileInputStream = new FileInputStream(fotografDosyaAdresi);
            fileInputStream.read(fotografDosyasi);
            Path path = Paths.get(fotografDosyaAdresi);
            byte[] data = Files.readAllBytes(path);
            Fotograf fotograf = new Fotograf();
            fotograf.setImage(data);
            cv.setFotograf(fotograf);
            fileInputStream.close();

            //Kaydetme veya güncelleme işlemini yapalım.
            if (lblId.getText().equals("")) {
                cvService.save(cv);
                this.dispose();
            } else {
                cv.setId(new Long(lblId.getText()));
                cvService.update(cv);
                this.dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnFotografSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotografSecActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Resim dosyaları", "jpg", "png");
        fileChooser.addChoosableFileFilter(filter);
        int sonuc = fileChooser.showSaveDialog(null);

        if (sonuc == JFileChooser.APPROVE_OPTION) {
            File secilenDosya = fileChooser.getSelectedFile();
            String secilenDosyaAdresi = secilenDosya.getAbsolutePath();
            this.fotografDosyaAdresi = secilenDosyaAdresi;
            this.fotografDosyasi = new byte[(int) secilenDosyaAdresi.length()];
            lblFotograf.setIcon(ResizeImage(secilenDosyaAdresi));
        } else if (sonuc == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(this, "Dosya seçilmedi. İşleme devam edebilmek için lütfen bir dosya seçiniz!", "Dosya Seçilmedi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFotografSecActionPerformed

    public ImageIcon ResizeImage(String fotografKonumu) {
        ImageIcon fotograf = new ImageIcon(fotografKonumu);
        Image img = fotograf.getImage();
        Image newImg = img.getScaledInstance(lblFotograf.getWidth(), lblFotograf.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFotografSec;
    private javax.swing.JButton btnIptal;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JComboBox<String> cmbBolum;
    private javax.swing.JComboBox<String> cmbCinsiyet;
    private javax.swing.JComboBox<String> cmbIl;
    private javax.swing.JComboBox<String> cmbIlce;
    private javax.swing.JComboBox<String> cmbOkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFotograf;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtCvTanimi;
    private com.toedter.calendar.JDateChooser txtDogumTarihi;
    private javax.swing.JTextField txtEposta;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCKimlikNo;
    // End of variables declaration//GEN-END:variables
}
