/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.hrapp.ui;

import com.vektorel.hrapp.entity.Adres;
import com.vektorel.hrapp.entity.Departman;
import com.vektorel.hrapp.entity.Il;
import com.vektorel.hrapp.entity.Ilce;
import com.vektorel.hrapp.entity.Kisi;
import com.vektorel.hrapp.service.DepartmanService;
import com.vektorel.hrapp.service.IlService;
import com.vektorel.hrapp.service.IlceService;
import com.vektorel.hrapp.service.KisiService;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author takatas
 */
public class frmDepartmanEkle extends javax.swing.JDialog {

    DepartmanService departmanService = new DepartmanService();
    IlService ilService = new IlService();
    IlceService ilceService = new IlceService();
    KisiService kisiService = new KisiService();

    /**
     * Creates new form frmDepartmanEkle
     */
    public frmDepartmanEkle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        IlIlceComboDoldur();
        departmanTabloyuDoldur();
        //yoneticiDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDepartmanId = new javax.swing.JLabel();
        lblKod = new javax.swing.JLabel();
        txtKod = new javax.swing.JTextField();
        lblTanım = new javax.swing.JLabel();
        txtTanim = new javax.swing.JTextField();
        lblAdres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdres = new javax.swing.JTextArea();
        cmbYonetici = new javax.swing.JComboBox<>();
        lblYonetici = new javax.swing.JLabel();
        btnKaydet = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnKapat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDepartman = new javax.swing.JTable();
        txtTelefon = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblIl = new javax.swing.JLabel();
        lblIlce = new javax.swing.JLabel();
        cmbIl = new javax.swing.JComboBox<>();
        cmbIlce = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblKod.setText("Kod");

        lblTanım.setText("Tanım");

        lblAdres.setText("Açık Adres");

        txtAdres.setColumns(20);
        txtAdres.setRows(5);
        jScrollPane1.setViewportView(txtAdres);

        lblYonetici.setText("Yönetici");

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnKapat.setText("Kapat");
        btnKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKapatActionPerformed(evt);
            }
        });

        tblDepartman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDepartman);

        lblTelefon.setText("Telefon");

        lblEmail.setText("e-Mail");

        lblIl.setText("İl");

        lblIlce.setText("İlçe");

        cmbIl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbIlMouseClicked(evt);
            }
        });
        cmbIl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKaydet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKapat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDepartmanId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKod, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTanım)
                                    .addComponent(lblYonetici))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTanim)
                                    .addComponent(cmbYonetici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTelefon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEmail)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIl)
                                    .addComponent(lblIlce))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbIlce, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbIl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdres)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDepartmanId, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKod)
                            .addComponent(txtKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefon)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIl)
                            .addComponent(cmbIl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTanım)
                            .addComponent(txtTanim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIlce)
                            .addComponent(cmbIlce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbYonetici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYonetici)
                            .addComponent(lblAdres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKaydet)
                    .addComponent(btnGuncelle)
                    .addComponent(btnSil)
                    .addComponent(btnKapat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKapatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKapatActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        try {
            Adres adres = new Adres();

            Il il = ilService.getByIlAdi(cmbIl.getSelectedItem().toString());
            Ilce ilce = ilceService.getByIlceAdi(cmbIlce.getSelectedItem().toString());
            //Kisi kisi = kisiService.getByName(cmbYonetici.getSelectedItem().toString());

            adres.setAcikAdres(txtAdres.getText());
            adres.setTel(txtTelefon.getText());
            adres.setEposta(txtEmail.getText());
            adres.setIl(il);
            adres.setIlce(ilce);

            if (lblDepartmanId.getText().trim().equals("")) {
                departmanService.save(new Departman(null, txtKod.getText(), txtTanim.getText(), adres));
            } else {
                departmanService.update(new Departman(new Long(lblDepartmanId.getText()), txtKod.getText(), txtTanim.getText(), adres));
            }
            departmanTabloyuDoldur();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void cmbIlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIlActionPerformed

    }//GEN-LAST:event_cmbIlActionPerformed

    private void cmbIlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbIlMouseClicked

    }//GEN-LAST:event_cmbIlMouseClicked

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed

        int seciliKayit = tblDepartman.getSelectedRow();
        if (seciliKayit > -1) {
            String value = tblDepartman.getValueAt(seciliKayit, 0).toString();
            Departman departman = departmanService.getById(new Long(value));

            txtKod.setText(departman.getKod());
            txtTanim.setText(departman.getTanim());
            txtAdres.setText(departman.getAdres().getAcikAdres());
            txtTelefon.setText(departman.getAdres().getTel());
            txtEmail.setText(departman.getAdres().getEposta());
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        try {
            int seciliKayit = tblDepartman.getSelectedRow();
            if (seciliKayit > -1) {
                String value = tblDepartman.getValueAt(seciliKayit, 0).toString();
                Departman departman = departmanService.getById(new Long(value));
                departmanService.delete(departman);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Listeden Kayıt Seçiniz.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnKapat;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnSil;
    private javax.swing.JComboBox<String> cmbIl;
    private javax.swing.JComboBox<String> cmbIlce;
    private javax.swing.JComboBox<String> cmbYonetici;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdres;
    private javax.swing.JLabel lblDepartmanId;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIl;
    private javax.swing.JLabel lblIlce;
    private javax.swing.JLabel lblKod;
    private javax.swing.JLabel lblTanım;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblYonetici;
    private javax.swing.JTable tblDepartman;
    private javax.swing.JTextArea txtAdres;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKod;
    private javax.swing.JTextField txtTanim;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void yoneticiDoldur() {
        List<Kisi> yonetici = kisiService.getAll(null);
        String[] kisiData = new String[yonetici.size()];
        for (int i = 0; i < yonetici.size(); i++) {
            kisiData[i] = yonetici.get(i).getAdSoyad();
            cmbYonetici.addItem(yonetici.get(i).getAdSoyad());

        }

    }

    private void IlIlceComboDoldur() {

        List<Il> il = ilService.getAll(null);
        String[] ilData = new String[il.size()];
        for (int i = 0; i < il.size(); i++) {
            ilData[i] = il.get(i).getAd();
            cmbIl.addItem(il.get(i).getAd());

        }

        List<Ilce> ilce = ilceService.getAll(null);
        String[] ilceData = new String[il.size()];
        for (int i = 0; i < ilce.size(); i++) {
            ilceData[i] = ilce.get(i).getAd();
            cmbIlce.addItem(ilce.get(i).getAd());

        }

    }

    private void departmanTabloyuDoldur() {
        List<Departman> departman = departmanService.getAll(null);
        String[][] data = new String[departman.size()][8];
        for (int i = 0; i < departman.size(); i++) {
            data[i][0] = departman.get(i).getId().toString();
            data[i][1] = departman.get(i).getKod();
            data[i][2] = departman.get(i).getTanim();
            data[i][3] = departman.get(i).getAdres().getTel();
            data[i][4] = departman.get(i).getAdres().getEposta();
            data[i][5] = departman.get(i).getAdres().getIl().getAd();
            data[i][6] = departman.get(i).getAdres().getIlce().getAd();
        }

        tblDepartman.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Id",
                    "Kod", "Tanım", "Telefon", "e-Mail", "İl", "İlçe"
                }
        ));
    }

}
