/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.hrapp.ui.takatas;

import com.vektorel.hrapp.entity.service.takatas.IlService;
import com.vektorel.hrapp.entity.takatas.Il;

/**
 *
 * @author vektorel
 */
public class frmIlEkle extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public frmIlEkle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIlKod = new javax.swing.JLabel();
        txtIlKod = new javax.swing.JTextField();
        lblIlAd = new javax.swing.JLabel();
        txtIlAd = new javax.swing.JTextField();
        btnIlKaydet = new javax.swing.JButton();
        btnIlIptal = new javax.swing.JButton();
        lblIlId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIlKod.setText("Kod");

        lblIlAd.setText("Ad");

        btnIlKaydet.setText("Kaydet");
        btnIlKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIlKaydetActionPerformed(evt);
            }
        });

        btnIlIptal.setText("İptal");
        btnIlIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIlIptalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIlKod)
                    .addComponent(lblIlAd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIlId, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIlAd)
                        .addComponent(txtIlKod)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnIlIptal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addComponent(btnIlKaydet))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblIlId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIlKod)
                    .addComponent(txtIlKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIlAd)
                    .addComponent(txtIlAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIlKaydet)
                    .addComponent(btnIlIptal))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIlKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIlKaydetActionPerformed
        try {
            IlService ilService = new IlService();
            if (lblIlId.getText() == null) {
                ilService.save(new Il(null, txtIlKod.getText(), txtIlAd.getText()));
            } else {
                ilService.update(new Il(new Long(lblIlId.getText()), txtIlKod.getText(), txtIlAd.getText()));
            }

        } catch (Exception e) {
            e.getMessage();
        }

    }//GEN-LAST:event_btnIlKaydetActionPerformed

    private void btnIlIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIlIptalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIlIptalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIlIptal;
    private javax.swing.JButton btnIlKaydet;
    private javax.swing.JLabel lblIlAd;
    private javax.swing.JLabel lblIlId;
    private javax.swing.JLabel lblIlKod;
    private javax.swing.JTextField txtIlAd;
    private javax.swing.JTextField txtIlKod;
    // End of variables declaration//GEN-END:variables
}
